server:
  port: 8080
  servlet:
    contextPath: /hello

spring:
  jacksone:
    time: UTC
  resources:
    add-mappings: true
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
      show: false
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: secret

logging:
  level:
    org:
      springframework:
        web: ERROR
    com:
      sampleapp:
        helloworld: DEBUG

config:
  authUser: abhishek
  authPassword: '{noop}rajput'

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
      show: false
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: secret

logging:
    com:
      sampleapp:
        helloworld: Info

config:
  authUser: abhishek
  authPassword: '{noop}rajput'
