server:
  port: 8080
  servlet:
    contextPath: /hello

spring:
  jacksone:
    time: UTC
  resources:
    add-mappings: true
  profiles:
    active: default
logging:
  level:
    org:
      springframework:
        web: ERROR
    com:
      sampleapp:
        helloworld: INFO
