name: CI Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  clean-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          check-latest: true
      - name: Cached Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-v1-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - run: ( ./gradlew clean build )
        name: "Executing build"
